---
title: "Stacked Bar Plot/Genomics in infectious diseases"
author: "Abdallah"
date: "2026-05-31"
output: html_document
---

We load the desired libraries 
```{r}
library(tidyverse)
library(ggplot2)
```

We create a dataframe of all our elements
```{r}
data <- data.frame(
  Category = rep(c("Beta-lactam", "Efflux", "Target\nAlteration", 
                   "Macrolide/\nMLSB", "Aminoglycoside", 
                   "Tetracycline", "Other"), each = 2),
  Location = rep(c("Chromosomal","Plasmid"), 7),
  Count = c(1, 3,    
            11, 0,   
            3, 0,    
            1, 4,   
            2, 3,  
            1, 2,    
            1, 2)  
)
```

Now that our data frame is created we generate a chromosomal vs plasmid resitance distrubuation plot
```{r}
ggplot(data, aes(x = Category, y = Count, fill = Location)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_fill_manual(values = c("Chromosomal" = "#2C5F8A", 
                                "Plasmid" = "#E8834B")) +
  labs(
    title = "Chromosomal vs Plasmid ARG Distribution\nAcross Clinical S. aureus Isolates",
    x = "Resistance Mechanism Category",
    y = "Number of Unique ARGs",
    fill = "ARG Location",
   
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 14, face = "bold", hjust = 0.5),
    axis.text.x = element_text(size = 10),
    axis.text.y = element_text(size = 10),
    axis.title = element_text(size = 12),
    legend.title = element_text(size = 11),
    legend.text = element_text(size = 10),
    plot.caption = element_text(size = 8, hjust = 0.5),
    panel.grid.major.x = element_blank()
  )
```

Save as a tiff file
```{r}
ggsave(
  filename = "ARG_distribution.tiff",
  plot = last_plot(),
  width = 16,
  height = 10,
  units = "in",
  dpi = 600,
  bg = "white",
  compression = "lzw",
  limitsize = FALSE
)
```